String baseUrl = "https://dummyjson.com";
const String listScreen = "Products App";
const String cardScreen = "Details";
const String cartScreen = "Cart";
const String errorDialog = "Error";
const String continueButtonText = "Continue";
const String tryAgainButtonText = "Try again";
const String addToCartText = "Add to cart";
const String addedText = "Added";
